#!/bin/bash
# =============================================================================
# System Flow Validator for cot-reasoning v5.0.0
#
# Purpose: Validate that reasoning flows conform to the cot-reasoning output
#          contract, including the cost-tiered requirements per mode
#          (MINIMAL / BASIC / STANDARD / ENHANCED).
#
# Usage: ./validate-system-flow.sh [OPTIONS] <input_file_or_directory>
#
# Options:
#   -s, --single    Validate a single flow file (markdown)
#   -d, --directory Validate all flow files in a directory
#   -j, --json      Validate JSON structure (single flow or examples wrapper)
#   -m, --markdown  Validate Markdown structure (default)
#   -v, --verbose   Show detailed validation messages
#   -h, --help      Show this help message
#
# Examples:
#   ./validate-system-flow.sh -s output.md
#   ./validate-system-flow.sh -d ./flows/ -v
#   ./validate-system-flow.sh -j assets/system-examples.json
#
# Returns:
#   0 - All validations passed
#   1 - Validation errors found
#   2 - Usage error
# =============================================================================

set -uo pipefail

# =============================================================================
# Configuration
# =============================================================================

SCRIPT_NAME="validate-system-flow.sh"
VERSION="5.0.0"
SKILL_NAME="cot-reasoning"
GENERATED_BY="cot-reasoning v${VERSION}"

# Contract enums (must match SKILL.md)
VALID_MODES=("MINIMAL" "BASIC" "STANDARD" "ENHANCED")
VALID_TYPES=("ANALYTICAL" "CREATIVE" "CRITICAL" "SYSTEMATIC" "ETHICAL" "STRATEGIC")
VALID_PATTERNS=("Zero-Shot CoT" "Few-Shot CoT" "Auto-CoT" "Tree of Thoughts" "ReAct")
VALID_COMPLEXITIES=("LOW" "MEDIUM" "HIGH" "VERY_HIGH")
VALID_TOOLS=("filesystem-read" "filesystem-write" "shell-execution" "web-search" "code-search")

# MINIMAL mode hard boilerplate budget (must match SKILL.md)
MINIMAL_STRUCTURAL_BUDGET=12
MINIMAL_STEP_BUDGET=3

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Counters (reset per file)
ERRORS=0
WARNINGS=0
CHECKED=0
PASSED=0

# =============================================================================
# Helper Functions
# =============================================================================

log_info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[PASS]${NC} $1"; PASSED=$((PASSED + 1)); }
log_warning() { echo -e "${YELLOW}[WARN]${NC} $1"; WARNINGS=$((WARNINGS + 1)); }
log_error()   { echo -e "${RED}[ERROR]${NC} $1"; ERRORS=$((ERRORS + 1)); }

log_header() {
    echo -e "\n${BLUE}================================================================================${NC}"
    echo -e "${BLUE}$1${NC}"
    echo -e "${BLUE}================================================================================${NC}\n"
}

reset_counters() {
    ERRORS=0
    WARNINGS=0
    CHECKED=0
    PASSED=0
}

in_list() {
    local value="$1"
    shift
    local item
    for item in "$@"; do
        [[ "$value" == "$item" ]] && return 0
    done
    return 1
}

show_help() {
    cat << EOF
${SKILL_NAME} - System Flow Validator v${VERSION}

Usage: $SCRIPT_NAME [OPTIONS] <input>

Validate reasoning flows against the cot-reasoning output contract.
Validation is COST-TIERED: the checks applied depend on the flow's
Reasoning Mode (MINIMAL, BASIC, STANDARD, ENHANCED).

Options:
  -s, --single    Validate a single flow file (markdown)
  -d, --directory Validate all flow files in a directory
  -j, --json      Validate JSON structure (a single flow object or an
                  examples wrapper with an "examples" array)
  -m, --markdown  Validate Markdown structure (default)
  -v, --verbose   Show detailed validation messages
  -h, --help      Show this help message

Examples:
  $SCRIPT_NAME -s flow_output.md
  $SCRIPT_NAME -j assets/system-examples.json
  $SCRIPT_NAME -d ./test-flows/ -v

Validation Checks:
  - Core sections present (all modes)
  - Mode-conditional extended sections (tier-aware)
  - Step structure validity (fields required by the mode)
  - Reasoning Mode / Thinking Type / Complexity / Pattern values valid
  - Tool calls use the category-first taxonomy (no invented tool names)
  - Fallback paths defined (BASIC/STANDARD/ENHANCED)
  - Quality metrics present (BASIC/STANDARD/ENHANCED)
  - MINIMAL boilerplate budget: at most ${MINIMAL_STRUCTURAL_BUDGET} structural
    lines and at most ${MINIMAL_STEP_BUDGET} steps
  - Version consistency ("Generated By: ${GENERATED_BY}")

Return Codes:
  0 - All validations passed
  1 - Validation errors found
  2 - Usage error

EOF
    exit 2
}

# =============================================================================
# Markdown Validation
# =============================================================================

# Extract the value of a "**Label:** value" header field
field_value() {
    local content="$1"
    local label="$2"
    sed -n "s/.*\*\*${label}:\*\* *//p" <<< "$content" | head -1 | sed 's/ *$//'
}

# Count structural (non-content) lines: headings + header field labels
count_structural_lines() {
    local content="$1"
    local count=0
    local line
    while IFS= read -r line; do
        if [[ "$line" =~ ^# ]]; then
            count=$((count + 1))
        elif [[ "$line" =~ ^\*\*(Reasoning\ Mode|Thinking\ Type|Complexity|Steps):\*\* ]]; then
            count=$((count + 1))
        fi
    done <<< "$content"
    echo "$count"
}

validate_step_block() {
    local step_number="$1"
    local block="$2"
    local mode="$3"
    local required_fields=()

    case "$mode" in
        MINIMAL)
            required_fields=("Action" "Expected Output" "Validation")
            ;;
        BASIC)
            required_fields=("Thought" "Why" "Action" "Expected Output" "Validation" "Next Step" "Fallback")
            ;;
        ENHANCED)
            required_fields=("Why" "Action" "Expected Output" "Validation" "Next Step" "Fallback")
            ;;
        *)
            required_fields=("Thought" "Why" "Action" "Expected Output" "Validation" "Next Step" "Fallback")
            ;;
    esac

    local field
    for field in "${required_fields[@]}"; do
        CHECKED=$((CHECKED + 1))
        if grep -q "\*\*${field}:\*\*" <<< "$block"; then
            log_success "Step $step_number: $field present"
        else
            log_error "Step $step_number: Missing field - $field (required in $mode mode)"
        fi
    done

    # Tool field: category-first taxonomy
    CHECKED=$((CHECKED + 1))
    if grep -q "\*\*Tool:\*\*" <<< "$block"; then
        local tool
        tool=$(sed -n "s/.*\*\*Tool:\*\* *//p" <<< "$block" | head -1 | awk '{print $1}')
        if [[ "$tool" == "None" ]] || [[ -z "$tool" ]]; then
            log_success "Step $step_number: Tool is None (pure reasoning)"
        elif in_list "$tool" "${VALID_TOOLS[@]}"; then
            log_success "Step $step_number: Tool category valid - $tool"
            if ! grep -q "\*\*Tool Parameters:\*\*" <<< "$block"; then
                log_warning "Step $step_number: Tool specified but no Tool Parameters found"
            fi
        else
            log_error "Step $step_number: '$tool' is not a tool category (allowed: ${VALID_TOOLS[*]} or None)"
        fi
    fi
}

validate_markdown() {
    local file="$1"
    local content
    content=$(cat "$file" 2>/dev/null || "")

    if [[ -z "$content" ]]; then
        log_error "File is empty or unreadable: $file"
        return
    fi

    # ---- Core sections (mandatory in every mode) ----
    log_header "Checking Core Sections (all modes)"
    local core_sections=("Reasoning Flow:" "Reasoning Mode:" "Thinking Type:" "Complexity:" "Reasoning Steps" "Key Findings" "Recommendations")
    local section
    for section in "${core_sections[@]}"; do
        CHECKED=$((CHECKED + 1))
        if grep -q "$section" <<< "$content"; then
            log_success "Found: $section"
        else
            log_error "Missing core section: $section (required in every mode)"
        fi
    done

    # ---- Flow metadata values ----
    log_header "Checking Flow Metadata"
    local mode type complexity pattern

    CHECKED=$((CHECKED + 1))
    mode=$(field_value "$content" "Reasoning Mode")
    if [[ -n "$mode" ]]; then
        if in_list "$mode" "${VALID_MODES[@]}"; then
            log_success "Reasoning Mode is valid: $mode"
        else
            log_error "Invalid Reasoning Mode: '$mode' (must be one of: ${VALID_MODES[*]})"
            mode="STANDARD"
        fi
    else
        log_error "Reasoning Mode is missing"
        mode="STANDARD"
    fi

    CHECKED=$((CHECKED + 1))
    type=$(field_value "$content" "Thinking Type")
    if [[ -n "$type" ]]; then
        if in_list "$type" "${VALID_TYPES[@]}"; then
            log_success "Thinking Type is valid: $type"
        else
            log_error "Invalid Thinking Type: '$type' (must be one of: ${VALID_TYPES[*]})"
        fi
    else
        log_error "Thinking Type is missing"
    fi

    CHECKED=$((CHECKED + 1))
    complexity=$(field_value "$content" "Complexity")
    if [[ -n "$complexity" ]]; then
        if in_list "$complexity" "${VALID_COMPLEXITIES[@]}"; then
            log_success "Complexity is valid: $complexity"
        else
            log_error "Invalid Complexity: '$complexity' (must be one of: ${VALID_COMPLEXITIES[*]})"
        fi
    else
        log_error "Complexity is missing"
    fi

    CHECKED=$((CHECKED + 1))
    pattern=$(field_value "$content" "Pattern")
    if [[ -n "$pattern" ]]; then
        if in_list "$pattern" "${VALID_PATTERNS[@]}"; then
            log_success "Pattern is valid: $pattern"
        else
            log_error "Invalid Pattern: '$pattern' (must be one of: ${VALID_PATTERNS[*]})"
        fi
    else
        log_warning "No Pattern field found (recommended)"
    fi

    # ---- Mode-conditional extended sections ----
    log_header "Checking Extended Sections (mode: $mode)"
    local extended_sections=()
    case "$mode" in
        MINIMAL)
            ;;
        BASIC)
            extended_sections=("Problem Analysis" "Quality Metrics")
            ;;
        *)
            extended_sections=("Flow ID:" "Timestamp:" "Configuration" "Problem Analysis" "Intermediate Results" "Execution Summary" "Quality Metrics" "Meta Information")
            ;;
    esac
    for section in "${extended_sections[@]}"; do
        CHECKED=$((CHECKED + 1))
        if grep -q "$section" <<< "$content"; then
            log_success "Found: $section (required in $mode)"
        else
            log_error "Missing section: $section (required in $mode mode)"
        fi
    done

    # ---- Quality metrics (BASIC and above) ----
    if [[ "$mode" != "MINIMAL" ]]; then
        log_header "Checking Quality Metrics"
        local metrics=("Confidence Level" "Reasoning Quality" "Step Completion" "Actionability")
        local metric
        for metric in "${metrics[@]}"; do
            CHECKED=$((CHECKED + 1))
            if grep -q "\*\*${metric}:\*\*" <<< "$content"; then
                log_success "Found metric: $metric"
            else
                log_error "Missing quality metric: $metric (required in $mode mode)"
            fi
        done
    fi

    # ---- Version consistency ----
    log_header "Checking Version Consistency"
    CHECKED=$((CHECKED + 1))
    local generated_by
    generated_by=$(sed -n "s/.*\*\*Generated By:\*\* *//p" <<< "$content" | head -1)
    if [[ -n "$generated_by" ]]; then
        if [[ "$generated_by" == "$GENERATED_BY" ]]; then
            log_success "Generated By is consistent: $generated_by"
        else
            log_error "Generated By mismatch: '$generated_by' (expected: $GENERATED_BY)"
        fi
    else
        log_warning "No Generated By field found"
    fi

    # ---- Step structure ----
    log_header "Checking Step Structure (mode: $mode)"
    local step_count
    step_count=$(grep -c "^### Step [0-9]" <<< "$content" || true)

    CHECKED=$((CHECKED + 1))
    if [[ "$step_count" -eq 0 ]]; then
        log_error "No steps found in flow"
    else
        log_success "Found $step_count steps"
    fi

    if [[ "$mode" == "MINIMAL" && "$step_count" -gt "$MINIMAL_STEP_BUDGET" ]]; then
        CHECKED=$((CHECKED + 1))
        log_error "MINIMAL mode allows at most $MINIMAL_STEP_BUDGET steps; found $step_count"
    fi

    # Validate each step block
    local blocks=()
    local cur=""
    local line
    while IFS= read -r line; do
        if [[ "$line" =~ ^###\ Step\ [0-9]+: ]]; then
            if [[ -n "$cur" ]]; then
                blocks+=("$cur")
            fi
            cur="$line"$'\n'
        elif [[ -n "$cur" ]]; then
            if [[ "$line" =~ ^#{2,3}\  ]]; then
                blocks+=("$cur")
                cur=""
            else
                cur+="$line"$'\n'
            fi
        fi
    done <<< "$content"
    if [[ -n "$cur" ]]; then
        blocks+=("$cur")
    fi

    local i
    for i in "${!blocks[@]}"; do
        validate_step_block "$((i + 1))" "${blocks[$i]}" "$mode"
    done

    # ---- MINIMAL boilerplate budget ----
    if [[ "$mode" == "MINIMAL" ]]; then
        log_header "Checking MINIMAL Boilerplate Budget"
        local structural
        structural=$(count_structural_lines "$content")
        CHECKED=$((CHECKED + 1))
        log_info "Structural (non-content) lines: $structural (budget: $MINIMAL_STRUCTURAL_BUDGET)"
        if [[ "$structural" -le "$MINIMAL_STRUCTURAL_BUDGET" ]]; then
            log_success "MINIMAL flow within boilerplate budget ($structural <= $MINIMAL_STRUCTURAL_BUDGET)"
        else
            log_error "MINIMAL flow exceeds boilerplate budget ($structural > $MINIMAL_STRUCTURAL_BUDGET)"
        fi
    fi
}

# =============================================================================
# JSON Validation
# =============================================================================

json_has() {
    # json_has <file> <jq-path> -> exit 0 if the path exists and is not null/false
    local file="$1"
    local path="$2"
    jq -e "$path" "$file" > /dev/null 2>&1
}

json_has_key() {
    # json_has_key <file> <object-path> <key>
    local file="$1"
    local path="$2"
    local key="$3"
    jq -e "${path} | has(\"${key}\")" "$file" > /dev/null 2>&1
}

validate_json_step() {
    local file="$1"
    local prefix="$2"
    local index="$3"
    local mode="$4"
    local step_path="${prefix}.flow.steps[${index}]"
    local required_fields=()

    case "$mode" in
        MINIMAL)
            required_fields=("action" "expected_output" "validation")
            ;;
        BASIC)
            required_fields=("thought" "why" "action" "expected_output" "validation" "next_step" "fallback")
            ;;
        ENHANCED)
            required_fields=("why" "action" "expected_output" "validation" "next_step" "fallback")
            ;;
        *)
            required_fields=("thought" "why" "action" "tool" "input" "expected_output" "validation" "status" "next_step" "fallback")
            ;;
    esac

    local field
    for field in "${required_fields[@]}"; do
        CHECKED=$((CHECKED + 1))
        if json_has_key "$file" "$step_path" "$field"; then
            log_success "Step $((index + 1)): field '$field' present"
        else
            log_error "Step $((index + 1)): missing field '$field' (required in $mode mode)"
        fi
    done

    # Tool category check
    CHECKED=$((CHECKED + 1))
    local tool
    tool=$(jq -r "${step_path}.tool" "$file" 2>/dev/null)
    if [[ "$tool" == "null" || -z "$tool" ]]; then
        log_success "Step $((index + 1)): tool is null (pure reasoning)"
    elif in_list "$tool" "${VALID_TOOLS[@]}"; then
        log_success "Step $((index + 1)): tool category valid - $tool"
    else
        log_error "Step $((index + 1)): '$tool' is not a tool category (allowed: ${VALID_TOOLS[*]} or null)"
    fi
}

validate_json_example() {
    local file="$1"
    local prefix="$2"
    local label="$3"

    log_header "Validating JSON ${label}"

    # ---- Enum fields ----
    local mode type complexity pattern

    CHECKED=$((CHECKED + 1))
    mode=$(jq -r "${prefix}.mode // empty" "$file" 2>/dev/null)
    if in_list "$mode" "${VALID_MODES[@]}"; then
        log_success "mode is valid: $mode"
    else
        log_error "Invalid mode: '$mode' (must be one of: ${VALID_MODES[*]})"
        mode="STANDARD"
    fi

    CHECKED=$((CHECKED + 1))
    type=$(jq -r "${prefix}.thinking_type // empty" "$file" 2>/dev/null)
    if in_list "$type" "${VALID_TYPES[@]}"; then
        log_success "thinking_type is valid: $type"
    else
        log_error "Invalid thinking_type: '$type' (must be one of: ${VALID_TYPES[*]})"
    fi

    CHECKED=$((CHECKED + 1))
    complexity=$(jq -r "${prefix}.complexity // empty" "$file" 2>/dev/null)
    if in_list "$complexity" "${VALID_COMPLEXITIES[@]}"; then
        log_success "complexity is valid: $complexity"
    else
        log_error "Invalid complexity: '$complexity' (must be one of: ${VALID_COMPLEXITIES[*]})"
    fi

    CHECKED=$((CHECKED + 1))
    pattern=$(jq -r "${prefix}.pattern // empty" "$file" 2>/dev/null)
    if in_list "$pattern" "${VALID_PATTERNS[@]}"; then
        log_success "pattern is valid: $pattern"
    else
        log_error "Invalid pattern: '$pattern' (must be one of: ${VALID_PATTERNS[*]})"
    fi

    # ---- Steps ----
    CHECKED=$((CHECKED + 1))
    local step_count
    step_count=$(jq -r "${prefix}.flow.steps | length" "$file" 2>/dev/null || echo 0)
    if [[ "$step_count" -gt 0 ]]; then
        log_success "Found $step_count steps"
    else
        log_error "No steps found in flow"
    fi

    if [[ "$mode" == "MINIMAL" && "$step_count" -gt "$MINIMAL_STEP_BUDGET" ]]; then
        CHECKED=$((CHECKED + 1))
        log_error "MINIMAL mode allows at most $MINIMAL_STEP_BUDGET steps; found $step_count"
    fi

    local i
    for ((i = 0; i < step_count; i++)); do
        validate_json_step "$file" "$prefix" "$i" "$mode"
    done

    # ---- Findings and recommendations ----
    CHECKED=$((CHECKED + 1))
    local findings_count
    findings_count=$(jq -r "${prefix}.flow.key_findings | length" "$file" 2>/dev/null || echo 0)
    if [[ "$findings_count" -gt 0 ]]; then
        log_success "Found $findings_count key findings"
    else
        log_error "key_findings is empty or missing"
    fi

    CHECKED=$((CHECKED + 1))
    local rec_count
    rec_count=$(jq -r "${prefix}.flow.recommendations | length" "$file" 2>/dev/null || echo 0)
    if [[ "$rec_count" -gt 0 ]]; then
        log_success "Found $rec_count recommendations"
    else
        log_error "recommendations is empty or missing"
    fi

    # ---- Mode-conditional sections ----
    if [[ "$mode" != "MINIMAL" ]]; then
        CHECKED=$((CHECKED + 1))
        if json_has "$file" "${prefix}.flow.problem_analysis"; then
            log_success "problem_analysis present (required in $mode)"
        else
            log_error "problem_analysis missing (required in $mode mode)"
        fi

        CHECKED=$((CHECKED + 1))
        if json_has "$file" "${prefix}.flow.quality_metrics"; then
            log_success "quality_metrics present (required in $mode)"
        else
            log_error "quality_metrics missing (required in $mode mode)"
        fi

        local metric_keys=("confidence_level" "reasoning_quality" "step_completion" "actionability")
        local key
        for key in "${metric_keys[@]}"; do
            CHECKED=$((CHECKED + 1))
            if json_has_key "$file" "${prefix}.flow.quality_metrics" "$key"; then
                log_success "quality_metrics.$key present"
            else
                log_error "quality_metrics.$key missing (required in $mode mode)"
            fi
        done
    fi

    if [[ "$mode" == "STANDARD" || "$mode" == "ENHANCED" ]]; then
        local extended=("flow_id" "timestamp" "configuration" "intermediate_results" "execution_summary" "meta")
        local field
        for field in "${extended[@]}"; do
            CHECKED=$((CHECKED + 1))
            if json_has "$file" "${prefix}.flow.${field}"; then
                log_success "flow.$field present (required in $mode)"
            else
                log_error "flow.$field missing (required in $mode mode)"
            fi
        done

        CHECKED=$((CHECKED + 1))
        local generated_by
        generated_by=$(jq -r "${prefix}.flow.meta.generated_by // empty" "$file" 2>/dev/null)
        if [[ "$generated_by" == "$GENERATED_BY" ]]; then
            log_success "meta.generated_by is consistent: $generated_by"
        else
            log_error "meta.generated_by mismatch: '$generated_by' (expected: $GENERATED_BY)"
        fi
    fi
}

validate_json_file() {
    local file="$1"

    log_header "Checking JSON Structure"

    if ! command -v jq > /dev/null 2>&1; then
        log_error "jq is required for JSON validation. Install with: sudo apt-get install jq"
        return
    fi

    CHECKED=$((CHECKED + 1))
    if jq empty "$file" > /dev/null 2>&1; then
        log_success "Valid JSON structure"
    else
        log_error "Invalid JSON structure"
        return
    fi

    # Examples wrapper or single flow object?
    if json_has "$file" ".examples"; then
        CHECKED=$((CHECKED + 1))
        local wrapper_version
        wrapper_version=$(jq -r ".metadata.version // empty" "$file" 2>/dev/null)
        if [[ "$wrapper_version" == "$VERSION" ]]; then
            log_success "Wrapper metadata.version is consistent: $wrapper_version"
        else
            log_error "Wrapper metadata.version mismatch: '$wrapper_version' (expected: $VERSION)"
        fi

        local count
        count=$(jq -r ".examples | length" "$file" 2>/dev/null || echo 0)
        local i
        for ((i = 0; i < count; i++)); do
            validate_json_example "$file" ".examples[${i}]" "example[$i] ($(jq -r ".examples[${i}].id // \"?\"" "$file"))"
        done
    else
        validate_json_example "$file" "" "flow"
    fi
}

# =============================================================================
# Main Validation Function
# =============================================================================

validate_file() {
    local file="$1"
    local is_json="$2"

    if [[ ! -f "$file" ]]; then
        log_error "File not found: $file"
        return 1
    fi

    log_header "Validating: $file"

    reset_counters

    if [[ "$is_json" == "true" ]]; then
        validate_json_file "$file"
    else
        validate_markdown "$file"
    fi

    # Summary
    echo ""
    log_header "Validation Summary for: $file"
    echo -e "  Checks:     $CHECKED"
    echo -e "  Passed:     ${GREEN}$PASSED${NC}"
    echo -e "  Warnings:   ${YELLOW}$WARNINGS${NC}"
    echo -e "  Errors:     ${RED}$ERRORS${NC}"
    echo ""

    if [[ $ERRORS -eq 0 ]]; then
        echo -e "${GREEN}OK: All validations passed!${NC}"
        return 0
    else
        echo -e "${RED}FAIL: Validation failed with $ERRORS error(s)${NC}"
        return 1
    fi
}

# =============================================================================
# Main Script Execution
# =============================================================================

main() {
    local mode="markdown"
    local verbose="false"
    local target=""

    while [[ $# -gt 0 ]]; do
        case "$1" in
            -s|--single)
                mode="single"
                shift
                ;;
            -d|--directory)
                mode="directory"
                shift
                ;;
            -j|--json)
                mode="json"
                shift
                ;;
            -m|--markdown)
                mode="markdown"
                shift
                ;;
            -v|--verbose)
                verbose="true"
                shift
                ;;
            -h|--help)
                show_help
                ;;
            *)
                if [[ -z "$target" ]]; then
                    target="$1"
                fi
                shift
                ;;
        esac
    done

    if [[ -z "$target" ]]; then
        show_help
    fi

    if [[ ! -e "$target" ]]; then
        log_error "Target does not exist: $target"
        exit 2
    fi

    log_header "${SKILL_NAME} - System Flow Validator v${VERSION}"
    echo -e "Mode:       $mode"
    echo -e "Target:     $target"
    echo -e "Verbose:    $verbose"
    echo ""

    case "$mode" in
        "single")
            if [[ "$target" == *.json ]]; then
                validate_file "$target" "true"
                exit $?
            else
                validate_file "$target" "false"
                exit $?
            fi
            ;;
        "directory")
            local total_errors=0
            local total_checks=0
            local total_passed=0
            local files_processed=0
            local file

            while IFS= read -r -d "" file; do
                if [[ -f "$file" ]]; then
                    files_processed=$((files_processed + 1))
                    if [[ "$file" == *.json ]]; then
                        validate_file "$file" "true" || true
                    else
                        validate_file "$file" "false" || true
                    fi
                    total_errors=$((total_errors + ERRORS))
                    total_checks=$((total_checks + CHECKED))
                    total_passed=$((total_passed + PASSED))
                    echo ""
                fi
            done < <(find "$target" -type f \( -name "*.md" -o -name "*.json" \) -print0)

            log_header "Directory Validation Summary"
            echo -e "  Files:      $files_processed"
            echo -e "  Checks:     $total_checks"
            echo -e "  Passed:     ${GREEN}$total_passed${NC}"
            echo -e "  Errors:     ${RED}$total_errors${NC}"
            echo ""

            if [[ $total_errors -eq 0 ]]; then
                echo -e "${GREEN}OK: All files passed validation!${NC}"
                exit 0
            else
                echo -e "${RED}FAIL: $total_errors validation error(s) found${NC}"
                exit 1
            fi
            ;;
        "json")
            if [[ -f "$target" && "$target" == *.json ]]; then
                validate_file "$target" "true"
                exit $?
            else
                log_error "JSON validation requires a .json file"
                exit 2
            fi
            ;;
        "markdown")
            if [[ -f "$target" && "$target" == *.md ]]; then
                validate_file "$target" "false"
                exit $?
            else
                log_error "Markdown validation requires a .md file"
                exit 2
            fi
            ;;
        *)
            if [[ "$target" == *.json ]]; then
                validate_file "$target" "true"
                exit $?
            else
                validate_file "$target" "false"
                exit $?
            fi
            ;;
    esac
}

main "$@"
